#!/usr/bin/env node
// Build step: reads all YAML source files under data/ and writes data.js.
// Run with `npm run build` whenever you edit YAML files.

'use strict';

const fs   = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const ROOT    = path.join(__dirname, '..');
const dataDir = path.join(ROOT, 'data');

function readYaml(filePath) {
  return yaml.load(fs.readFileSync(filePath, 'utf8'));
}

function globYaml(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.yml'))
    .sort()
    .map(f => path.join(dir, f));
}

// ─── portraits ───────────────────────────────────────────────────────────────

const PORTRAITS = readYaml(path.join(dataDir, 'portraits.yml'));

// ─── definitions ─────────────────────────────────────────────────────────────

const definitions = {
  talents:   readYaml(path.join(dataDir, 'definitions', 'talents.yml'))   || {},
  abilities: readYaml(path.join(dataDir, 'definitions', 'abilities.yml')) || {},
  heroic:    readYaml(path.join(dataDir, 'definitions', 'heroic.yml'))    || {},
};

// ─── gear_db ─────────────────────────────────────────────────────────────────

const gearDir  = path.join(dataDir, 'gear');
const gear_db  = [];
for (const filePath of globYaml(gearDir)) {
  const items = readYaml(filePath) || [];
  for (const item of items) {
    const entry = { n: item.name, s: item.slot };
    if (item.location)    entry.l   = item.location;
    if (item.act != null) entry.a   = item.act;
    if (item.description) entry.d   = item.description;
    if (item.category)    entry.cat = item.category;
    gear_db.push(entry);
  }
}

// ─── MC builds ───────────────────────────────────────────────────────────────

const mc_builds = [];
const archetypesMC = {};
const extrasMC = {};

const mcRoot = path.join(dataDir, 'mc');
if (fs.existsSync(mcRoot)) {
  // Preserve theme order: alphabetical by theme dir, builds sorted by filename
  for (const themeDir of fs.readdirSync(mcRoot).sort()) {
    const themePath = path.join(mcRoot, themeDir);
    if (!fs.statSync(themePath).isDirectory()) continue;

    for (const filePath of globYaml(themePath)) {
      const b = readYaml(filePath);
      mc_builds.push({
        theme:  b.theme,
        name:   b.name,
        origin: b.origin || null,
        levels: b.levels || {},
      });
      if (b.archetypes) archetypesMC[b.name] = b.archetypes;
      if (b.extras)     extrasMC[b.name]     = b.extras;
    }
  }
}

// ─── companion builds ────────────────────────────────────────────────────────

const companions = {};
const archetypesCOMP = {};
const extrasComp = {};

const compRoot = path.join(dataDir, 'companions');
if (fs.existsSync(compRoot)) {
  // Companion order is defined by COMPANION_ORDER in app.js; we just load whatever dirs exist
  for (const charName of fs.readdirSync(compRoot).sort()) {
    const charPath = path.join(compRoot, charName);
    if (!fs.statSync(charPath).isDirectory()) continue;

    const variants = [];
    for (const filePath of globYaml(charPath)) {
      const b = readYaml(filePath);
      variants.push({
        name:   b.name,
        levels: b.levels || {},
      });
      if (b.archetypes) archetypesCOMP[b.name] = b.archetypes;
      if (b.extras)     extrasComp[b.name]     = b.extras;
    }
    if (variants.length) companions[charName] = variants;
  }
}

// ─── assemble DATA ────────────────────────────────────────────────────────────

const DATA = {
  mc_builds,
  companions,
  definitions,
  gear_db,
  archetypes: { mc: archetypesMC, comp: archetypesCOMP },
  extras:     { mc_extras: extrasMC, comp_extras: extrasComp },
};

// ─── write data.js ────────────────────────────────────────────────────────────

const out = [
  '// Generated by `npm run build` — edit the YAML files in data/ instead.',
  `const DATA = ${JSON.stringify(DATA)};`,
  `const PORTRAITS = ${JSON.stringify(PORTRAITS)};`,
  '',
].join('\n');

fs.writeFileSync(path.join(ROOT, 'data.js'), out);

const kb = Math.round(Buffer.byteLength(out) / 1024);
console.log(`✓ data.js  (${kb} KB)`);
console.log(`  mc_builds:    ${mc_builds.length}`);
console.log(`  companions:   ${Object.values(companions).reduce((s, v) => s + v.length, 0)} variants across ${Object.keys(companions).length} characters`);
console.log(`  gear_db:      ${gear_db.length} items`);
console.log(`  talents:      ${Object.keys(definitions.talents).length}`);
console.log(`  abilities:    ${Object.keys(definitions.abilities).length}`);
console.log(`  heroic:       ${Object.keys(definitions.heroic).length}`);
